name: Smoke test "austen" build

on: 
  workflow_dispatch:

  push:
    branches: [main, actions-test]
    paths:
      - 'containers/austen/**'
  pull_request:
    branches:
      - main
    paths:
      - 'containers/austen/**'

env:
  REGISTRY: ghcr.io
  CONTAINER_NAME: austen
  IMAGE_NAME: ${{ github.repository }}/austen

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'

  smoke-test:
    name: Smoke test
    if: "!contains(github.event.head_commit.message, 'Automated update') && !contains(github.event.head_commit.message, 'CI ignore')"
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      id: checkout
      uses: actions/checkout@v2

    - name: Log in to the Container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: containers/${{ env.CONTAINER_NAME }}/.devcontainer/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        
    - name: Smoke test
      id: smoke_test
      uses: ./.github/actions/smoke-test
      with:
        definition: ${{ env.CONTAINER_NAME }}
        image: mcr.microsoft.com/vscode/devcontainers/base:dev-ubuntu
        user: vscode
